// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlertDialog(arg1, arg2) {
  return window['go']['main']['App']['AlertDialog'](arg1, arg2);
}

export function CheckAllServerStatus() {
  return window['go']['main']['App']['CheckAllServerStatus']();
}

export function CheckServerStatus(arg1) {
  return window['go']['main']['App']['CheckServerStatus'](arg1);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function DeleteFirewall(arg1) {
  return window['go']['main']['App']['DeleteFirewall'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function Deploy(arg1, arg2) {
  return window['go']['main']['App']['Deploy'](arg1, arg2);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetAllFirewalls() {
  return window['go']['main']['App']['GetAllFirewalls']();
}

export function GetAllHistory() {
  return window['go']['main']['App']['GetAllHistory']();
}

export function GetAllTemplates() {
  return window['go']['main']['App']['GetAllTemplates']();
}

export function GetAppFullName() {
  return window['go']['main']['App']['GetAppFullName']();
}

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetFirewall(arg1) {
  return window['go']['main']['App']['GetFirewall'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReloadData() {
  return window['go']['main']['App']['ReloadData']();
}

export function ResetAll() {
  return window['go']['main']['App']['ResetAll']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveFirewall(arg1) {
  return window['go']['main']['App']['SaveFirewall'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2);
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['main']['App']['WriteFileContent'](arg1, arg2);
}
