// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AlertDialog(arg1:string,arg2:string):Promise<void>;

export function CheckAllServerStatus():Promise<void>;

export function CheckServerStatus(arg1:number):Promise<string>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<string>;

export function DeleteFirewall(arg1:number):Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function Deploy(arg1:number,arg2:string):Promise<model.DeployHistory>;

export function ExportData():Promise<string>;

export function GetAllFirewalls():Promise<Array<model.Firewall>>;

export function GetAllHistory():Promise<Array<model.DeployHistory>>;

export function GetAllTemplates():Promise<Array<model.Template>>;

export function GetAppFullName():Promise<string>;

export function GetAppName():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<model.Config>;

export function GetConfigDir():Promise<string>;

export function GetFirewall(arg1:number):Promise<model.Firewall>;

export function GetTemplate(arg1:string):Promise<model.Template>;

export function ImportData(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReloadData():Promise<void>;

export function ResetAll():Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveFirewall(arg1:string):Promise<void>;

export function SaveHistory(arg1:string):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;

export function WriteFileContent(arg1:string,arg2:string):Promise<void>;
